-- Updated schema for dashboard with user authentication and analytics

-- Create invites table with analytics tracking
create table invites (
  id bigint generated by default as identity primary key,
  token text unique not null,
  user_id uuid references auth.users(id) on delete cascade, -- Owner of this URL
  recipient_name text not null, -- e.g., "Sakshi"
  first_opened_at timestamp with time zone, -- When first viewed
  total_visits integer default 0, -- Count of page loads
  visit_timestamps timestamp with time zone[] default '{}', -- Array of all visit timestamps
  no_clicks integer default 0, -- Count of "No" button clicks
  yes_timestamps timestamp with time zone[] default '{}', -- Array of all "Yes" click timestamps
  first_yes_at timestamp with time zone, -- When "Yes" was clicked for the very first time
  used boolean default false, -- "Yes" clicked?
  used_at timestamp with time zone, -- When "Yes" was clicked (Latest)
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Index for faster lookups
create index idx_invites_token on invites(token);
create index idx_invites_user_id on invites(user_id);

-- Enable RLS (Row Level Security)
alter table invites enable row level security;

-- RLS Policies

-- Users can only see their own invites
create policy "Users can view own invites"
on invites for select
using (auth.uid() = user_id);

-- Users can only create invites for themselves
create policy "Users can create own invites"
on invites for insert
with check (auth.uid() = user_id);

-- Users can update their own invites
create policy "Users can update own invites"
on invites for update
using (auth.uid() = user_id);

-- Anyone can update invite analytics by token (for tracking visits and "Yes" clicks)
create policy "Public can update invite by token"
on invites for update
using (token is not null);

-- Function to increment visit counter
create or replace function increment_visits(url_token text)
returns void as $$
begin
  update invites
  set total_visits = total_visits + 1
  where token = url_token;
end;
$$ language plpgsql security definer;
